### PR TITLE
Fix official sample

### PR DESCRIPTION
**Pull request by jdeantoni**
add the tfsm example to the example folder + minor changes

### CODE REVIEW

**Comment by ebousse** [comment]
Strange, why is the ECA check not working? @jdeantoni is your Eclipse account well configured and connected to your Github account?

**Comment by jdeantoni** [comment]
Strange indeed, this is not the first time I have a problem like this one...
I re-validated... Let's wait and see....

**Comment by jdeantoni** [comment]
This is really strange since I can see contradictory information:
image
On top we can see that my mail has a correct ECA but the red part refuse the account :-/

**Comment by ebousse** [comment]
I think I have found the problem, you have attached the following identity to your commits:
```
Author: jdeantoni <julien.deantoni@univ-cotedazur.fr>
```
while the email address you used at Eclipse is @inria.fr.

You can retry after changing your git identity in your GEMOC git repos with `git config user.email`… but you will also need to either amend your commits and redo them with the new configured identity :(

**Comment by dvojtise** [comment]
If we do a squash and merge (withe the correct sign-of-by ), there is no strong need to amend as soon as someone has checked the content (I didn't had time to do it yet)

**Pull request closed without merging**
